FROM python:3.9 AS production
LABEL maintainer="huaxlin <featureoverload@gmail.com>"


# Setup Pypi
ARG PyPI_CN_HOST=pypi.doubanio.com
ARG PyPI_CN_REPO=https://${PyPI_CN_HOST}/simple
#ARG PyPI_PRI_HOST=pypi.private.com
#ARG PyPI_PRI_REPO=http://${PyPI_PRI_HOST}/root/public/+simple

RUN echo "[global]" > /etc/pip.conf \
 && echo "index-url = ${PyPI_CN_REPO}" >> /etc/pip.conf \
# && echo "extra-index-url = ${PyPI_PRI_REPO}" >> /etc/pip.conf \
 && echo "[install]" >> /etc/pip.conf \
 && echo "trusted-host = ${PyPI_CN_HOST}" >> /etc/pip.conf \
# && echo "               ${PyPI_PRI_HOST}" >> /etc/pip.conf \
 && python -m pip install -U pip \
 && python -m pip install wheel
ENV TZ=Asia/Shanghai


RUN mkdir /code
COPY music_recommender/ /code/music_recommender/
COPY music_recommender.joblib /code/music_recommender.joblib
COPY venv39/ /venv39/
ENV PYTHONPATH=/code


WORKDIR /app/

RUN /venv39/bin/python3 -m pip install -U pip \
 && /venv39/bin/python3 -m pip install -U wheel

RUN /venv39/bin/python3 -m pip install uvicorn[standard]==0.15.0 gunicorn==20.1.0
RUN /venv39/bin/python3 -m pip install fastapi==0.68.1 pydantic==1.10.2

COPY app.py /app/app.py
ENV PYTHONPATH "$PYTHONPATH:/app"

CMD ["/venv39/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--log-level", "debug"]
